/**
 * Exact counsel-facing disclaimer (founder-approved wording).
 */
export const LAYER_DECISION_DISCLAIMER =
  'Data on this site is generated by AI and machine learning models and is provided for informational purposes only; you alone are responsible for any decisions made based on it.'

export const GLOBAL_PROTOTYPE_BANNER =
  'Full-product mockup · live Open-Meteo for selected district(s); peer ranks use same rules on seasonal climate proxies (no live NDVI). Rule-based environmental conduciveness — not production guarantees.'
